import Vue, { PluginObject } from 'vue';
import Component from 'vue-class-component';

import { ModulVue } from '../../utils/vue/vue';
import { ERROR_PAGE_NOT_FOUND } from '../component-names';
import ErrorTemplatePlugin from '../error-template/error-template';
import I18nPlugin from '../i18n/i18n';
import LinkPlugin from '../link/link';
import MessagePlugin from '../message/message';
import PanelPlugin from '../panel/panel';
import WithRender from './error-page-not-found.html?style=./error-page-not-found.scss';

@WithRender
@Component
export class MErrorPageNotFound extends ModulVue {

    // @Prop({
    //     default: () => (Vue.prototype as any).$i18n.translate('m-error-technical-difficulty:title')
    // })
    // public title: string;

    // @Prop({
    //     default: () => [
    //         new Link((Vue.prototype as any).$i18n.translate('m-error-technical-difficulty:help'), 'https://www.ene.ulaval.ca/contactez-nous?systeme_en_cours=81'),
    //         new Link((Vue.prototype as any).$i18n.translate('m-error-technical-difficulty:home-label'), '\\')]
    // })
    // public links: Link[];

    // @Prop({
    //     default: () => [
    //         (Vue.prototype as any).$i18n.translate('m-error-technical-difficulty:hint.primary'),
    //         (Vue.prototype as any).$i18n.translate('m-error-technical-difficulty:hint.secondary')]
    // })
    // public hints: string[];

    // @Prop({
    //     default: () => moment()
    // })
    // public errorDate: moment.Moment;

    // /**
    //  * Reference number must be generated by the parent component
    //  */
    // @Prop()
    // public errorReferenceNumber?: string;

    // @Prop({
    //     default: false
    // })
    // public showStackTrace: boolean;

    // /**
    //  * Javascript Error containing the stack trace to be displayed
    //  */
    // @Prop()
    // public error?: Error;

    // readonly skin: string = MErrorTemplateSkin.Error;

    // readonly iconeName: string = 'error';

    // get userAgent(): string {
    //     return window.navigator.userAgent;
    // }

    // get dateInfo(): string[] | undefined {
    //     let result: string[] | undefined = undefined;
    //     if (this.errorDate) {
    //         result = [this.errorDate.format('YYYY-MM-DD'), this.errorDate.format('HH:mm:ss')];
    //     }
    //     return result;
    // }

    // get propStacktrace(): boolean {
    //     return this.showStackTrace && !!this.error && !!this.error.stack;
    // }
}

const ErrorPageNotFoundPlugin: PluginObject<any> = {
    install(v, options): void {
        v.prototype.$log.debug(ERROR_PAGE_NOT_FOUND, 'plugin.install');
        v.use(I18nPlugin);
        v.use(LinkPlugin);
        v.use(MessagePlugin);
        v.use(PanelPlugin);
        v.use(ErrorTemplatePlugin);
        v.component(ERROR_PAGE_NOT_FOUND, MErrorPageNotFound);
    }
};

export default ErrorPageNotFoundPlugin;
